/*
Genere un SQL que Presente el nombre 
del departamento, ubicación, apellidos, cargo y salario de los empleados
que trabajan en la ubicación 1800.
*/
SELECT D.DEPARTMENT_NAME [NOMBRE DEL DEPARTAMENTO], L.LOCATION_ID [UBICACIÓN],
E.LAST_NAME [APELLIDOS], E.JOB_ID [CARGO], E.SALARY [SALARIO]
FROM DEPARTMENT D
INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE L.LOCATION_ID = 1800


/*
Genere un SQL que indique Cuáles empleados han repetido cargo en la empresa.
*/

SELECT E.EMPLOYEES_ID [ID EMPLEADO], E.FIRST_NAME [NOMBRE], 
E.LAST_NAME, E.JOB_ID
FROM EMPLOYEES E
INNER JOIN (SELECT EMPLOYEES_ID  FROM JOB_HISTORY   
	GROUP BY EMPLOYEES_ID
   	HAVING COUNT(DISTINCT CARGO) > 1
) JH 
ON E.EMPLOYEES_ID = JH.EMPLOYEES_ID


/*
6.	Crear una vista que permita consultar los empleados que no tengan jefe (manager_id)
y que permita filtrar por nombre de departamento y por nombre de país. 
*/

CREATE VIEW EMPLEADOS_SIN_JEFE_VISTA AS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, P.COUNTRY_NAME
FROM EMPLEADOS E
JOIN DEPARTAMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN PAIS P ON E.COUNTRY_ID = P.COUNTRY_ID
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE M.EMPLOYEE_ID IS NULL;

SELECT *
FROM EMPLEADOS_SIN_JEFE_VISTA
WHERE DEPARTMENT_NAME = 'NOMBRE DEL DEPARTAMENTO'
AND COUNTRY_NAME = 'NOMBRE DEL PAÍS';





